CREATE TABLE Users (
  ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  Name VARCHAR(255) NOT NULL,
  Email VARCHAR(255) NOT NULL,
  DecryptTest VARBINARY(255) NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE CoinFlipHistory (
  ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  UserID BIGINT UNSIGNED NOT NULL,
  DateTime VARBINARY(255) NOT NULL,
  Outcome VARBINARY(255) NOT NULL,
  HeadsAction VARBINARY(255),
  TailsAction VARBINARY(255),
  PRIMARY KEY (ID),
  FOREIGN KEY (UserID) REFERENCES Users(ID)
);
